Interractions i navbaren done og routes lavet i index
P3-Group-SW3/P3-Group-Project pull request #48
Opened 2024-11-01 13:44 UTC by FelixBjerre

2024-11-01 13:44 UTC, FelixBjerre commented
Jeg har lavet en pull request

2024-11-03 00:09 UTC, Emandersen requested changes
Du har committet .idea/misc.xml, kunne være fedt at den ikke var med i dine commits, ellers ser det fint ud.

2024-11-03 00:11 UTC, Emandersen approved these changes
Forkert knap

2024-11-04 08:25 UTC, wefjyl approved these changes

2024-11-04 08:27 UTC, merged